name: Commit Push
on:
  workflow_dispatch:
jobs:
    commit:
        runs-on: ubuntu-latest                                                                                  
        steps:
        - name: Checkout repository
          uses: actions/checkout@v2
          
        - name: Make changes to a file                                
          run: |
           echo "New content" >> path/to/file.txt
           
        - name: Commit changes
          run: |
            git config user.email "actions@github.com"
            git config user.name "GitHub Actions"
            git add .
            git commit -m "Update files via GitHub Actions"
            
        - name: Push changes
          run: |                                                                                                                                                                                                                                                                                                                                                                                                                              
            git push origin HEAD:main
            
        - name: Push changes
          run: |
            git push origin HEAD:main
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
