name: helloWorldDockerImage

on: 
  push:
    branches:
      - Terraform-Assignment-02

jobs:
  hello-world:
    runs-on: self-hosted
 
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: pull docker hello-world image
        run: docker pull hello-world

      - name: run docker hello-world image
        run: docker run hello-world
        