name: "Terraform-apply-infrastructure"

on:
  push:
    branches:
      - temp

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.ACCESS_KEY}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.SECRET_KEY}}
      AWS_REGION: 'ap-south-1'
    steps: 

      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: path
        run: cd Terraform-Assignment

      - name: Terraform Init
        id: init
        run: |
              cd Terraform-Assignment
              terraform init

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'push'
        run: |
             cd Terraform-Assignment
             terraform plan -no-color
        continue-on-error: true

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        if: github.event_name == 'push'
        run: |
             cd Terraform-Assignment
             terraform apply -auto-approve

      - name: Terraform Destroy
        id: destroy
        run: |
             cd Terraform-Assignment
             terraform destroy -auto-approve
