name: "Terraform-apply-infr"

on:
  push:
    branches:
      - GithubActions-Assignment 

jobs:
  terraform:
    name: "Terraform"
    runs-on: self-hosted
    defaults:
      run:
        working-directory: GithubActions-Assignment

    steps: 
        
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Setup Nodejs
        uses: actions/setup-node@v1
        
      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'push'
        run: terraform plan -no-color
        continue-on-error: true

      - name: Terraform Apply
        if: github.event_name == 'push'
        run: terraform apply -auto-approve

      - name: Terraform Destroy
        id: destroy
        run: terraform destroy -auto-approve
